#!/bin/sh

# Script used to build statically linked binaries
set -e

# Flags for static executable
STATIC="-lmingw32 -lSDL2main -lSDL2 -mwindows -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid -lhid -lsetupapi -static-libgcc -static"

if [[ $(uname | xargs) == "Linux" ]]; then
    [[ $1 == "release" ]] || make clean
    make chip8
    [[ ! -e bin/ ]] && mkdir bin/
    mv chip8 bin/chip8
    if [[ $1 == "release" ]]; then
        sha1sum bin/chip8 > bin/chip8.sha1sum
    fi
    exit 0
fi

# Build for Windows
[[ $1 == "release" ]] || make clean
make "STATIC=$STATIC" chip8
[[ ! -e bin/ ]] && mkdir bin/
mv chip8.exe bin/chip8.exe
if [[ $1 == "release" ]]; then
    sha1sum bin/chip8.exe > bin/chip8.exe.sha1sum
fi
