#!/bin/sh

# Script used to build statically linked binaries
set -e

# Flags for static executable
STATIC="-lmingw32 -lSDL2main -lSDL2 -mwindows -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid -lhid -lsetupapi -static-libgcc -static"

if [[ $(uname | xargs) == "Linux" ]]; then
    make clean; make chip8
    exit 0
fi

# Build for Windows
make clean
make "STATIC=$STATIC" chip8

