#!/bin/sh

# Script mostly used for Windows systems running on MINGW64
set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <ROM file path>"
    exit 1
fi

if [[ $(uname | xargs) == "Linux" ]]; then
    make FILE="$1" run
    exit 0
fi

# Build for Windows
make && ./chip8.exe "$1" > log

